version: "3.9"

services:
  web:
    build: .
    command: 
      - sh
      - -c
      - |
        python -m pip install pandas
        python -m pip install Pillow
        python -m pip install requests
        python -m pip install scikit-learn
        python -m pip install tensorflow
        python -m pip install keras
        python -m pip install matplotlib
        python -m pip install opencv-python
        python -m pip install django-simple-history
        python -m pip install python-decouple
        pip install django_ratelimit
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
