# Generated by Django 4.1.5 on 2023-10-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuarioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anterior', models.CharField(max_length=80)),
                ('descricao_anterior', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastrousuario')),
            ],
            options={
                'db_table': 'CadastroUsuarioHistorico',
            },
        ),
    ]
