# Generated by Django 5.0 on 2024-01-04 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalcustomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
