# Generated by Django 4.1.5 on 2023-09-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastrousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='name',
            new_name='nome',
        ),
    ]
