# Generated by Django 4.1.5 on 2023-09-24 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_registro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrousuario',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
