# Generated by Django 4.1.5 on 2023-09-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cadastrousuario_registration_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cadastrousuario',
            table='CadastroUsuario',
        ),
    ]
