# Generated by Django 5.0 on 2024-01-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofilehistory_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilehistory',
            name='email',
        ),
    ]
