# Generated by Django 5.0 on 2024-01-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofilehistory_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
